version: "3.9"
services:
  db:
    env_file: .env
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    build: .
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=sticky-notes-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - "${POSTGRES_SOURCE_DIR_PATH}:/etc/postgresql"
      - "${POSTGRES_LOGS_DIR_PATH}:/var/log/postgresql"
      - "${POSTGRES_LOGS_LIB_PATH}:/var/lib/postgresql"